### ISSUE TITLE
Pull indentation highlight out into its own plugin

### ISSUE THREAD

**Issue by phrohdoh** [tweekmonster/braceless.vim#2]
I'd love to have [this indentation guide](https://cloud.githubusercontent.com/assets/111942/13040915/11a1cf74-d380-11e5-8e56-da487f0536f8.gif) in brace-bearing languages as well.

I'm not very well versed in viml but did read `indent.vim` a bit, with a bit of guidance I could probably do this.

Do you think this is feasible?

**Comment by tweekmonster** [comment]
I didn't think that this would be the feature that stood out in this plugin, but sure.  I'll have something up in an hour or so :neckbeard:

**Comment by ezimir** [comment]
Would it be also possible for the `BracelessIndent` highlight to have configurable colors (cterm and gui)? Or simply re-defining that highlight in .vimrc will do it?

**Comment by tweekmonster** [comment]
So, "an hour or so" turned out to be three.  Here's a separate local indent plugin: https://github.com/tweekmonster/local-indent.vim

> Would it be also possible for the BracelessIndent highlight to have configurable colors (cterm and gui)? Or simply re-defining that highlight in .vimrc will do it?

Yup, you just need to redefine it yourself.  It's set as a `default` so it'll only be defined by the plugin if it doesn't already exist.  I don't use gvim, so I didn't test it with gui colors.  Hope it works out!

**Comment by phrohdoh** [comment]
Cool!
I'll play with it some more later as I'm not quite getting the results you're demonstrating.

Thanks!
