### ISSUE TITLE
Non greedy folding ?

### ISSUE THREAD

**Issue by amigrave** [tweekmonster/braceless.vim#22]
Is it possible to use braceless with a folding that would operate only on `def`, `class` and markers `{{{`  `}}}` instead of all indentations ?

**Comment by tweekmonster** [comment]
I could easily add a way to configure which blocks to fold on.  I would have to look into the fold markers, so no promises there.

**Comment by amigrave** [comment]
You mean user configurable block identifiers !? That would be cool indeed !

I don't know how markers works under the hood (I don't know vimscript in fact) but as they allow one to declare custom folding they are quite handy.

**Comment by tweekmonster** [comment]
@amigrave Yup, I'm working on configurable block folding.  The issue off the top of my head with fold markers is that braceless deals with inferred block endings, not explicit ones.  Something like this might not work out well:

``` python
def example1():
    # line 1
    # {{{
    # line 3
    pass

def example2():
    # line 1
    # }}}
    # line 3
    pass
```

I know that's not that likely to happen on purpose, but could happen in pastes.  I do want to add folding for collection symbols (`()`, `[]`, and `{}`), but that's something I want to tackle after I've figured out a better way to handle `foldexpr`.  It's still pretty slow even with caching and it most likely could be sped up by doing "good enough" block scanning instead of getting the true block boundaries.  So, I'd rather not slow it down by checking for explicit start and end symbols before using block boundaries at the moment.

**Comment by tweekmonster** [comment]
You can set folds for `def` or `class` using this in your configs:

``` vim
let braceless#pattern#python = {
\  'fold': '\<\%(def\|class\)\>\_.\{-}:\s*\%(\_$\|#\)'
\ }
```
