### ISSUE TITLE
Statement continuation slash inserted when a row of text in a docstring ends in 'and'.

### ISSUE THREAD

**Issue by jperras** [tweekmonster/braceless.vim#26]
When _editing_ an existing docstring of a function, having a line end in an `and` word causes the `/` line continuation operator to be inserted when adding a carriage return at the end of said line, most likely because Braceless believes itself to be within a conditional statement:

``` python
    def do_something():
        """
        Attempt to do something.

        When I get to the end of the line then hit enter to continue to the next line and \
            a slash character for statement continuations is inserted.
        """
```

**Comment by tweekmonster** [comment]
@jperras Thanks!  I knew it felt too easy adding this feature :sweat:

While we're here, a quick preview of auto-formatting I'm working on.

![autoformat](https://cloud.githubusercontent.com/assets/111942/13965699/bd8080ec-f045-11e5-97ce-4b40a964bd49.gif)

**Comment by jperras** [comment]
@tweekmonster o.O that's pretty neat. I've used `gqip` to reflow paragraphs of text before, but this is pretty great! :tada:

**Comment by tweekmonster** [comment]
@jperras Took me more than a few minutes to push a fix because I found issues with docstring indentation when adding new lines (they were indenting to the previous block even if they weren't inside them).

> o.O that's pretty neat. I've used gqip to reflow paragraphs of text before, but this is pretty great! :tada:

Thanks :grinning:  In addition to this, I'm also going to be adding line joining as well:

![join-lines](https://cloud.githubusercontent.com/assets/111942/13968000/822667e0-f050-11e5-9c5e-7b466cd12bb6.gif)

Reflowing code is filled with minor inconveniences that add up to a big pain in my ass and I want to resolve it with fewer keystrokes :smile:

**Comment by jperras** [comment]
Really digging the line joining examples – that's something I do _all_ the time when refactoring.
